#Config version, do not change this
version: 1

#Write interval to refresh the query (in minutes)
interval: 3

#Do you want to add the server this plugin is running on slots?
add_self_slots: true

#Write your server IPs and ports like this:

# 19132: server.myip.com
#WARNING!!! If you write IP like this:
#19132:server.myip.com, plugin won't crash, but it won't change slots

servers:
 19132: "play.example.com"
 19754: "my.server.net"